language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: mvn clean test
env:
  global:
    secure: j6wRCTC0DInwwB3/enLCI0DRUpb0GQQinTPCsGwv1CrBRPLzMsKmdRNFENYi9T4VCVA/aEFjzssVSv4ea1WCWuXd8VxKBQKW8rTotgW8bA81yV2ZuTZulG5jlr3tHZd0vpcGd9LMHbI4CFsosCoZ74leKR0FLP4Yw0GaKdIiXgChKtPz3UD3N5kHAZkzosIG+vujf/mZxzu7+nBiAPQ30p5ctk/4A+HkFALEtr6kZH48kF7JJIS39oQkb/zPFHhlsst+VVAaAQ6X2chm5MCjizwSEJnB+yPpfgQ7csorIp7CgQbE0FZJDaOh2g6ZREZWr5Q0d8gdq8hMFzAIDz5b5G6xVm/T4nxKElgBAcXfb1DgKddKK0+EsrwfX5QdAPiXo2x9aMWPxKU9tyNqwEE3nrn/QwdHNyNYc5sIbg19nW3uojBAdwN7vLrfJMyB62liTpplKpC/rXZ8elmVkswwB8hxl0awZuIRCzdA9oav/RBGmwJnZnCPwnAb/UuQk85PO8A9o3+P4IFU5JuQ3URBt+mxY4rauLndbgNZ8q1JfGEJbqMlYTutDHdchTSb9qmN5FM8bBj551BaevppGigdgg2Lo4rZC1VNaTnJfwaBFa3fuCSMU2EIch4bQnXX+gIXrkTpIbGjPiPttI/TvAbG68JwUx3kK7r6p8qeHfxO3HY=
